[LAB-2] - Created order screen
Yulno/flutter_coffee_shop pull request #2
Opened 2024-03-24 18:02 UTC by Yulno

2024-04-03 14:55 UTC, bushuevmaxim requested changes
код мне нравится, но данные не используются с апи
снекбар тоже не работает
продукты из списка 1 лабы)
доработай до пятницы либо единичку ставлю за задание

ответь тут, пожалуйста

2024-04-03 15:38 UTC, Yulno commented
@bushuevmaxim
Дорабатываю
Можно время до конца недели?

2024-04-04 00:06 UTC, bushuevmaxim commented
Можно до воскресенья. Мне до понедельника нужно проверить. В воскресенье с утра буду проверять и вечером до 7.30 вечера

2024-04-08 14:26 UTC, bushuevmaxim commented
какая у тебя версия флаттера
я не понимаю в чем проблема белый экран просто показывает у меня

2024-05-15 13:07 UTC, merged